// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tekstile.Context;

#nullable disable

namespace Tekstile.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250428212418_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tekstile.Data.Boyalar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcilanAdet")
                        .HasColumnType("int");

                    b.Property<int?>("BitenAdet")
                        .HasColumnType("int");

                    b.Property<decimal?>("BoyaFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BoyaKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoyaTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GelenAdet")
                        .HasColumnType("int");

                    b.Property<int?>("KovaAdedi")
                        .HasColumnType("int");

                    b.Property<string>("RenkAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StokDurum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Boyalar");
                });

            modelBuilder.Entity("Tekstile.Data.DesenBoyalar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoyaId")
                        .HasColumnType("int");

                    b.Property<int>("DesenId")
                        .HasColumnType("int");

                    b.Property<decimal?>("GramMiktari")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BoyaId");

                    b.HasIndex("DesenId");

                    b.ToTable("DesenBoyalari");
                });

            modelBuilder.Entity("Tekstile.Data.Desenler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Boyasayisi")
                        .HasColumnType("int");

                    b.Property<string>("DesenAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Desenler");
                });

            modelBuilder.Entity("Tekstile.Data.Kumascinsleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Gramaj")
                        .HasColumnType("int");

                    b.Property<string>("IplikTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KumasAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kumascinsleri");
                });

            modelBuilder.Entity("Tekstile.Data.Makineler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MakineAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Makineler");
                });

            modelBuilder.Entity("Tekstile.Data.Musteriler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YetkiliAdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("Tekstile.Data.Siparisler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Adet")
                        .HasColumnType("int");

                    b.Property<decimal?>("BaskiFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DesenId")
                        .HasColumnType("int");

                    b.Property<int>("KumasId")
                        .HasColumnType("int");

                    b.Property<int>("MakineId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DesenId");

                    b.HasIndex("KumasId");

                    b.HasIndex("MakineId");

                    b.HasIndex("MusteriId");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("Tekstile.Data.DesenBoyalar", b =>
                {
                    b.HasOne("Tekstile.Data.Boyalar", "Boya")
                        .WithMany("DesenBoyalars")
                        .HasForeignKey("BoyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tekstile.Data.Desenler", "Desen")
                        .WithMany("DesenBoyalars")
                        .HasForeignKey("DesenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boya");

                    b.Navigation("Desen");
                });

            modelBuilder.Entity("Tekstile.Data.Desenler", b =>
                {
                    b.HasOne("Tekstile.Data.Musteriler", "Musteri")
                        .WithMany("Desenlers")
                        .HasForeignKey("MusteriId");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("Tekstile.Data.Siparisler", b =>
                {
                    b.HasOne("Tekstile.Data.Desenler", "Desen")
                        .WithMany("Siparislers")
                        .HasForeignKey("DesenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tekstile.Data.Kumascinsleri", "Kumas")
                        .WithMany("Siparislers")
                        .HasForeignKey("KumasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tekstile.Data.Makineler", "Makine")
                        .WithMany("Siparislers")
                        .HasForeignKey("MakineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tekstile.Data.Musteriler", "Musteri")
                        .WithMany("Siparislers")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desen");

                    b.Navigation("Kumas");

                    b.Navigation("Makine");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("Tekstile.Data.Boyalar", b =>
                {
                    b.Navigation("DesenBoyalars");
                });

            modelBuilder.Entity("Tekstile.Data.Desenler", b =>
                {
                    b.Navigation("DesenBoyalars");

                    b.Navigation("Siparislers");
                });

            modelBuilder.Entity("Tekstile.Data.Kumascinsleri", b =>
                {
                    b.Navigation("Siparislers");
                });

            modelBuilder.Entity("Tekstile.Data.Makineler", b =>
                {
                    b.Navigation("Siparislers");
                });

            modelBuilder.Entity("Tekstile.Data.Musteriler", b =>
                {
                    b.Navigation("Desenlers");

                    b.Navigation("Siparislers");
                });
#pragma warning restore 612, 618
        }
    }
}
